version: '3.1'
services:
  samba:
    image: dperson/samba
    restart: always
    ports:
      - 139:139
      - 445:445
    volumes:
      - ${DATA_DIR:-../data}:/mount
    environment:
      TZ: America/Chicago
      USERID: ${UID:-1000}
      GROUPID: ${GID:-1000}
      SHARE: ${SAMBA_SHARE_NAME:-bluefan_store};/mount
networks:
  default:
    name: samba
    driver: bridge
