version: '3.1'

services:

  gluetun:
    image: qmcgaw/gluetun
    restart: always
    ports:
      - 8888:8888 # HTTP proxy
      - 8080
      - 9091
    volumes:
      - ${GLUETUN_CONFIG_DIR:-./config/gluetun}:/gluetun
    networks:
      - home
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    environment:
      VPN_SERVICE_PROVIDER: nordvpn
      OPENVPN_USER: ${NORDVPN_USERNAME}
      OPENVPN_PASSWORD: ${NORDVPN_PASSWORD}
      SERVER_REGIONS: United States
      HTTPPROXY: enabled
      TZ: America/Chicago

  transmission:
    image: linuxserver/transmission
    restart: unless-stopped
    volumes:
      - ${TRANSMISSION_CONFIG_DIR:-./config/transmission}:/config
      - ${DATA_DIR:-./data}/.torrents:/downloads
      - ${DATA_DIR:-./data}/.torrents/watch:/watch
    networks:
      - home
    network_mode: "service:gluetun"
    environment:
      TZ: America/Chicago
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
    cap_add:
      - NET_ADMIN

  sabnzbd:
    image: linuxserver/sabnzbd
    restart: unless-stopped
    volumes:
      - ${SABNZBD_CONFIG_DIR:-./config/sabnzbd}:/config
      - ${DATA_DIR:-./data}/.usenet/complete:/downloads
      - ${DATA_DIR:-./data}/.usenet/incomplete:/incomplete-downloads
    networks:
      - home
    network_mode: "service:gluetun"
    environment:
      TZ: America/Chicago
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}

  radarr:
    image: cr.hotio.dev/hotio/radarr
    restart: unless-stopped
    ports:
      - 7878
    volumes:
      - ${RADARR_CONFIG_DIR:-./config/radarr}:/config
      - ${DATA_DIR:-./data}:/data
    networks:
      - home
    depends_on:
      - jackett
      - transmission
      - sabnzbd
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      UMASK: 002
      TZ: America/Chicago

  sonarr:
    image: cr.hotio.dev/hotio/sonarr
    restart: unless-stopped
    ports:
      - 8989
    volumes:
      - ${SONARR_CONFIG_DIR:-./config/sonarr}:/config
      - ${DATA_DIR:-./data}:/data
    networks:
      - home
    depends_on:
      - jackett
      - transmission
      - sabnzbd
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      UMASK: 002
      TZ: America/Chicago

  readarr:
    image: cr.hotio.dev/hotio/readarr
    restart: unless-stopped
    ports:
      - 8787
    volumes:
      - ${READARR_CONFIG_DIR:-./config/readarr}:/config
      - ${DATA_DIR:-./data}:/data
    networks:
      - home
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      UMASK: 002
      TZ: America/Chicago

  prowlarr:
    image: cr.hotio.dev/hotio/prowlarr
    restart: unless-stopped
    ports:
      - 9696
    volumes:
      - ${PROWLARR_CONFIG_DIR:-./config/prowlarr}:/config
    networks:
      - home
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      UMASK: 002
      TZ: America/Chicago

  overseerr:
    image: sctx/overseerr:latest
    restart: unless-stopped
    ports:
      - 5055
    volumes:
      - ${OVERSEER_CONFIG_DIR:-./config/overseerr}:/app/config
    networks:
      - home
    environment:
      TZ: America/Chicago
      LOG_LEVEL: debug

  jackett:
    image: linuxserver/jackett:latest
    restart: unless-stopped
    ports:
      - 9117
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR:-./data}/.torrents/watch:/downloads
      - ${JACKETT_CONFIG_DIR:-./config/jackett}:/config
    networks:
      - home
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: America/Chicago

  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      #- 1900:1900/udp
      #- 5353/udp
      #- 8324:8324/tcp
      #- 32410:32410/udp
      #- 32412:32412/udp
      #- 32413/udp
      #- 32414:32414/udp
      #- 32469:32469/tcp
    volumes:
      - ${PLEX_CONFIG_DIR:-./config/plex}:/config
      - ${DATA_DIR:-./data}:/data
    networks:
      - home
    environment:
      TZ: America/Chicago
      ADVERTISE_IP: http://192.168.1.32:32400
      PLEX_UID: ${UID:-1000}
      PLEX_GID: ${GID:-1000}

  jellyfin:
    image: linuxserver/jellyfin
    restart: unless-stopped
    ports:
      - 8096
      - 7359:7359/udp #optional
      #- 8920:8920 #optional
      #- 1900:1900/udp #optional
    volumes:
      - ${JELLYFIN_CONFIG_DIR:-./config/jellyfin}:/config
      - ${DATA_DIR:-./data}:/data
    networks:
      - home
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: America/Chicago
      JELLYFIN_PublishedServerUrl: http://192.168.1.32 #optional

networks:
  home:
    name: home
    driver: bridge
