version: '3.1'

services:

  pihole:
    image: pihole/pihole:latest
    restart: always
    ports:
      - 53/tcp
      - 53/udp
      - 80/tcp
    volumes:
      - '${PIHOLE_CONFIG_DIR:-./config/pihole}:/etc/pihole'
      - '${DNSMASQ_CONFIG_DIR:-./config/dnsmasq}:/etc/dnsmasq.d'
    networks:
      home:
        ipv4_address: 10.0.1.2
    environment:
      TZ: America/Chicago
      WEBPASSWORD: 'pass'
      PIHOLE_UID: ${UID:-1000}
      PIHOLE_GID: ${GID:-1000}

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager
    restart: always
    ports:
      - '80:80'
      - '81'
      - '443:443'
    volumes:
      - ./config/nginx-proxy-manager:/data
      - ./config/letsencrypt:/etc/letsencrypt
    networks:
      home:
        ipv4_address: 10.0.1.3

  gluetun:
    image: qmcgaw/gluetun
    restart: always
    ports:
      - 8888:8888 # HTTP proxy
      - 8080
      - 9091
    volumes:
      - ${GLUETUN_CONFIG_DIR:-./config/gluetun}:/gluetun
    networks:
      home:
        ipv4_address: 10.0.1.4
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    environment:
      VPN_SERVICE_PROVIDER: nordvpn
      OPENVPN_USER: ${NORDVPN_USERNAME}
      OPENVPN_PASSWORD: ${NORDVPN_PASSWORD}
      SERVER_REGIONS: United States
      HTTPPROXY: enabled
      TZ: America/Chicago

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - home
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

  samba:
    image: dperson/samba
    restart: always
    ports:
      - 139:139
      - 445:445
    volumes:
      - ${DATA_DIR:-./data}:/mount
    networks:
      home:
        ipv4_address: 10.0.1.5
    environment:
      TZ: America/Chicago
      USERID: ${UID:-1000}
      GROUPID: ${GID:-1000}
      SHARE: bluefan_store;/mount

  homer:
    image: b4bz/homer
    restart: unless-stopped
    ports:
      - 8080
    volumes:
      - ${HOMER_CONFIG_DIR:-./config/homer/}:/www/assets
    networks:
      home:
        ipv4_address: 10.0.1.6

  transmission:
    image: linuxserver/transmission
    restart: unless-stopped
    volumes:
      - ${TRANSMISSION_CONFIG_DIR:-./config/transmission}:/config
      - ${DATA_DIR:-./data}/.torrents:/downloads
      - ${DATA_DIR:-./data}/.torrents/watch:/watch
    networks:
      - home
    network_mode: "service:gluetun"
    environment:
      TZ: America/Chicago
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
    cap_add:
      - NET_ADMIN

  sabnzbd:
    image: linuxserver/sabnzbd
    restart: unless-stopped
    volumes:
      - ${SABNZBD_CONFIG_DIR:-./config/sabnzbd}:/config
      - ${DATA_DIR:-./data}/.usenet/downloads:/downloads
      - ${DATA_DIR:-./data}/.usenet/incomplete:/incomplete-downloads
    networks:
      - home
    network_mode: "service:gluetun"
    environment:
      TZ: America/Chicago
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}

  radarr:
    image: cr.hotio.dev/hotio/radarr
    restart: unless-stopped
    ports:
      - 7878
    volumes:
      - ${RADARR_CONFIG_DIR:-./config/radarr}:/config
      - ${DATA_DIR:-./data}:/data
    networks:
      home:
        ipv4_address: 10.0.1.7
    depends_on:
      - jackett
      - transmission
      - sabnzbd
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      UMASK: 002
      TZ: America/Chicago

  sonarr:
    image: cr.hotio.dev/hotio/sonarr
    restart: unless-stopped
    ports:
      - 8989
    volumes:
      - ${SONARR_CONFIG_DIR:-./config/sonarr}:/config
      - ${DATA_DIR:-./data}:/data
    networks:
      home:
        ipv4_address: 10.0.1.8
    depends_on:
      - jackett
      - transmission
      - sabnzbd
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      UMASK: 002
      TZ: America/Chicago

  jackett:
    image: linuxserver/jackett:latest
    restart: unless-stopped
    ports:
      - 9117
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR:-./data}/.torrents/watch:/downloads
      - ${JACKETT_CONFIG_DIR:-./config/jackett}:/config
    networks:
      home:
        ipv4_address: 10.0.1.9
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: America/Chicago

  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 1900:1900/udp
      - 5353/udp
      - 8324:8324/tcp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413/udp
      - 32414:32414/udp
      - 32469:32469/tcp
    volumes:
      - ${PLEX_CONFIG_DIR:-./config/plex}:/config
      - ${DATA_DIR:-./data}:/data
    networks:
      home:
        ipv4_address: 10.0.1.10
    environment:
      TZ: America/Chicago
      ADVERTISE_IP: http://192.168.1.32:32400
      PLEX_UID: ${UID:-1000}
      PLEX_GID: ${GID:-1000}

  mealie:
    image: hkotel/mealie:latest
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - ${DATA_DIR:-./data}/.mealie:/app/data
    networks:
      home:
        ipv4_address: 10.0.1.11
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: America/Chicago
      RECIPE_PUBLIC: 'true'
      RECIPE_SHOW_NUTRITION: 'true'
      RECIPE_SHOW_ASSETS: 'true'
      RECIPE_LANDSCAPE_VIEW: 'true'
      RECIPE_DISABLE_COMMENTS: 'true'
      RECIPE_DISABLE_AMOUNT: 'false'

  gitlab:
    image: gitlab/gitlab-ee
    restart: unless-stopped
    ports:
      - 80
      - 443
      - 22
    volumes:
      - ${GITLAB_CONFIG_DIR:-./config/gitlab}:/etc/gitlab
      - ${GITLAB_LOG_DIR:-./logs/gitlab}/:/var/log/gitlab
      - ${DATA_DIR:-./data}:/var/opt/gitlab
    networks:
      home:
        ipv4_address: 10.0.1.12
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.everly.home'
    shm_size: 256m

networks:
  home:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/16
          gateway: 10.0.1.1
