version: '3.1'

services:

  dns:
    image: pihole/pihole:latest
    restart: always
    ports:
      - 53/tcp
      - 53/udp
      - 80/tcp
    volumes:
      - './pihole/config:/etc/pihole'
      - './pihole/dnsmasq:/etc/dnsmasq.d'
    networks:
      everly.home:
        ipv4_address: 10.0.1.2
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'pass'
      VIRTUAL_HOST: dns.everly.home
      VIRTUAL_PORT: 80

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - everly.home

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - everly.home
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

  torrent:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    ports:
      - 9091
      - 51413
      - 51413/udp
    volumes:
      - ./transmission/config:/config
      - ./transmission/downloads:/downloads
      - ./transmission/watch:/watch
    networks:
      - everly.home
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      TRANSMISSION_WEB_HOME: #optional
      USER: username #optional
      PASS: password #optional
      WHITELIST: #optional
      PEERPORT: #optional
      HOST_WHITELIST: #optional
      VIRTUAL_HOST: torrent.*
      VIRTUAL_PORT: 9091

  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
    volumes:
      - ./plex/config:/config
      - ./plex/data:/data
    networks:
      - everly.home
    environment:
      TZ: America/Chicago

  mealie:
    image: hkotel/mealie:latest
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - ./mealie/data/:/app/data
    networks:
      - everly.home
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      RECIPE_PUBLIC: 'true'
      RECIPE_SHOW_NUTRITION: 'true'
      RECIPE_SHOW_ASSETS: 'true'
      RECIPE_LANDSCAPE_VIEW: 'true'
      RECIPE_DISABLE_COMMENTS: 'true'
      RECIPE_DISABLE_AMOUNT: 'false'
      VIRTUAL_HOST: mealie.*

networks:
  everly.home:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/16
          gateway: 10.0.1.1
