version: '3.1'
services:
  gluetun:
    image: qmcgaw/gluetun
    restart: always
    ports:
      - 8888:8888 # HTTP proxy
      - 8080
      - 9091
    volumes:
      - ${GLUETUN_CONFIG_DIR:-./config/gluetun}:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    environment:
      VPN_SERVICE_PROVIDER: nordvpn
      OPENVPN_USER: ${NORDVPN_USERNAME}
      OPENVPN_PASSWORD: ${NORDVPN_PASSWORD}
      SERVER_REGIONS: United States
      HTTPPROXY: enabled
      TZ: America/Chicago
  transmission:
    image: linuxserver/transmission
    restart: unless-stopped
    volumes:
      - ${TRANSMISSION_CONFIG_DIR:-./config/transmission}:/config
      - ${DATA_DIR:-./data}/.torrents:/downloads
      - ${DATA_DIR:-./data}/.torrents/watch:/watch
    network_mode: "service:gluetun"
    environment:
      TZ: America/Chicago
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
    cap_add:
      - NET_ADMIN
  sabnzbd:
    image: linuxserver/sabnzbd
    restart: unless-stopped
    volumes:
      - ${SABNZBD_CONFIG_DIR:-./config/sabnzbd}:/config
      - ${DATA_DIR:-./data}/.usenet/complete:/downloads
      - ${DATA_DIR:-./data}/.usenet/incomplete:/incomplete-downloads
    network_mode: "service:gluetun"
    environment:
      TZ: America/Chicago
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
  radarr:
    image: cr.hotio.dev/hotio/radarr
    restart: unless-stopped
    ports:
      - 7878
    volumes:
      - ${RADARR_CONFIG_DIR:-./config/radarr}:/config
      - ${DATA_DIR:-./data}:/data
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      UMASK: 002
      TZ: America/Chicago
  sonarr:
    image: cr.hotio.dev/hotio/sonarr
    restart: unless-stopped
    ports:
      - 8989
    volumes:
      - ${SONARR_CONFIG_DIR:-./config/sonarr}:/config
      - ${DATA_DIR:-./data}:/data
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      UMASK: 002
      TZ: America/Chicago
  readarr:
    image: cr.hotio.dev/hotio/readarr
    restart: unless-stopped
    ports:
      - 8787
    volumes:
      - ${READARR_CONFIG_DIR:-./config/readarr}:/config
      - ${DATA_DIR:-./data}:/data
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      UMASK: 002
      TZ: America/Chicago
  prowlarr:
    image: cr.hotio.dev/hotio/prowlarr
    restart: unless-stopped
    ports:
      - 9696
    volumes:
      - ${PROWLARR_CONFIG_DIR:-./config/prowlarr}:/config
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      UMASK: 002
      TZ: America/Chicago
  overseerr:
    image: sctx/overseerr:latest
    restart: unless-stopped
    ports:
      - 5055
    volumes:
      - ${OVERSEER_CONFIG_DIR:-./config/overseerr}:/app/config
    environment:
      TZ: America/Chicago
      LOG_LEVEL: debug
networks:
  default:
    name: servarr
    driver: bridge
