version: '3.1'

services:

  bind9:
    image: internetsystemsconsortium/bind9:9.18
    restart: always
    ports:
      - 53/udp
      - 53/tcp
      - 953/tcp
    volumes:
      - ./bind9:/etc/bind
      - /var/cache/bind
      - /var/lib/bind
      - /var/log
    networks:
      everly.home:
        ipv4_address: 10.0.1.2

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432
    networks:
      everly.home:
        ipv4_address: 10.0.1.3
    dns:
      - "10.0.1.2"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    ports:
      - 9091
      - 51413
      - 51413/udp
    volumes:
      - ./transmission/config:/config
      - ./transmission/downloads:/downloads
      - ./transmission/watch:/watch
    networks:
      everly.home:
        ipv4_address: 10.0.1.4
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      TRANSMISSION_WEB_HOME: #optional
      USER: username #optional
      PASS: password #optional
      WHITELIST: #optional
      PEERPORT: #optional
      HOST_WHITELIST: #optional

  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
    volumes:
      - ./plex/config:/config
      - ./plex/data:/data
    networks:
      everly.home:
        ipv4_address: 10.0.1.5
    environment:
      TZ: America/Chicago

  mealie:
    image: hkotel/mealie:latest
    restart: unless-stopped
    ports:
      - 80
    networks:
      everly.home:
        ipv4_address: 10.0.1.6
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      RECIPE_PUBLIC: 'true'
      RECIPE_SHOW_NUTRITION: 'true'
      RECIPE_SHOW_ASSETS: 'true'
      RECIPE_LANDSCAPE_VIEW: 'true'
      RECIPE_DISABLE_COMMENTS: 'true'
      RECIPE_DISABLE_AMOUNT: 'false'
    volumes:
      - ./mealie/data/:/app/data

networks:
  everly.home:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/16
          gateway: 10.0.1.1
