version: '3.1'
services:
  mealie:
    image: hkotel/mealie:latest
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - ${DATA_DIR:-../data}/.mealie:/app/data
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: America/Chicago
      RECIPE_PUBLIC: true
      RECIPE_SHOW_NUTRITION: true
      RECIPE_SHOW_ASSETS: true
      RECIPE_LANDSCAPE_VIEW: true
      RECIPE_DISABLE_COMMENTS: true
      RECIPE_DISABLE_AMOUNT: false
networks:
  default:
    name: mealie
    driver: bridge
