version: '3.1'
services:
  home-assistant:
    image: homeassistant/home-assistant
    restart: unless-stopped
    ports:
      - 8123:8123
    volumes:
      - ${HOMEASSISTANT_CONFIG_DIR:-./config/homeassistant}:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: America/Chicago
networks:
  default:
    name: home-assistant
    driver: bridge
