version: '3.1'
services:
  homer:
    image: b4bz/homer
    restart: unless-stopped
    ports:
      - 8080
    volumes:
      - ${HOMER_CONFIG_DIR:-./config/}:/www/assets
    networks:
      - homer
networks:
  homer:
    name: homer
    driver: bridge
