version: '3.1'
services:
  calibre:
    restart: unless-stopped
    image: lscr.io/linuxserver/calibre
    ports:
      - 8080
      - 8081
    volumes:
      - ${DATA_DIR:-../data}/calibre:/config
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: America/Chicago
networks:
  default:
    name: calibre
    driver: bridge
